### PR TITLE
Merge Kcp

### PR DESCRIPTION
**Pull request by greatcat-taihe**

### CODE REVIEW

**Comment by greatcat-taihe** [comment]
merge kcp

**Comment by greatcat-taihe** [comment]
sorry, push to wrong respository

**Comment by marcosnils** [comment]
> sorry, push to wrong respository

hey @greatcat-taihe! this feature looks interesting even though it was sent to the wrong repository. Would it be any interest in contributing this to the upstream project?

**Comment by zihuyishi** [comment]
> > sorry, push to wrong respository
> 
> hey @greatcat-taihe! this feature looks interesting even though it was sent to the wrong repository. Would it be any interest in contributing this to the upstream project?

It has not well test, and I only run it on iOS and MacOS.
And server side also need a kcp acceptor, so I think there has lots of work to do.

**Comment by zihuyishi** [comment]
> > sorry, push to wrong respository
> 
> hey @greatcat-taihe! this feature looks interesting even though it was sent to the wrong repository. Would it be any interest in contributing this to the upstream project?

It has not well test, and I only run it on iOS and MacOS.
And server side also need a kcp acceptor, so I think there has lots of work to do.

**Pull request closed without merging**
