### PR TITLE
Add support for strongly typed JSON de/serialization

### PR DESCRIPTION
**Pull request by felippeduran**
This PR can be broken down into two steps. The first one prepares ground for strongly typed deserialization for JSON (without Protobuf generated classes) by unifying the IPitayaClient API. The second one adds Newtonsoft.Json and a new json serializer, deprecating the previous one.

In more detail, the first step does the following:
* Refactors `JsonSerializer` and `ProtobufSerializer` to use a single interface (`IPitayaSerializer`) and not be static.
* Renames `PitayaSerializer` to `SerializationFormat` inside `ProtobufSerializer` namespace.
* Deprecates all old methods, but keeps them for retrocompatibility.
* For the new unified methods, it decides which serializer to use based on the request object type (whether it implements `IMessage` or not).

And the second:
* Renames `JsonSerializer` to `LegacyJsonSerializer`.
* Keep `LegacyJsonSerializer` only on legacy methods (based on `string`s).
* Adds Newtonsoft.Json as a dependency.
* Adds a new `JsonSerializer` using Newtonsoft.Json.
* Fixes old, commented JSON unit tests.

This PR came from the current `IPitayaClient` API over complicating an implementation of an application specific client that will provide support to JSON, Protobuf and async Tasks. As it currently have multiple similar methods, this was leading to duplicated code and making tests annoying. Also, it'd be great to not be stuck with Protobuf when trying to implement strongly typed serialization.

### CODE REVIEW

**Comment by DylanGuedes** [comment]
I think you missed to add the changes to the changelog.

**Comment by felippeduran** [comment]
> I think you missed to add the changes to the changelog.

Done!

**Comment by DylanGuedes** [comment]
LGTM. Although I don't have permission to approval, so I'll look for someone (probably Hahn).

**Comment by leohahn** [comment]
Did you test `Newtonsoft.Json` with device builds? We had issues with this library in the past. Just to make sure we're testing this before merging.

**Comment by felippeduran** [comment]
> Did you test `Newtonsoft.Json` with device builds? We had issues with this library in the past. Just to make sure we're testing this before merging.

Not yet, good point. However, we use this one as a dependency of other internal libraries, so I think it should be fine. Once I test it, I'll let you know.

**Comment by felippeduran** [comment]
@leohahn, I've managed to test basic Newtonsoft.Json functionality in a separate project with success. I've build the game for iOS and ran it in the simulator. I used high stripping of managed code and "Fast but no Exceptions" optimization for script calls.

**Comment by leohahn** [comment]
LGTM

**Pull request merged**
